### ISSUE TITLE
How to compile msitools on ubuntu?

### ISSUE THREAD

**Issue by def-fun** [tm604/msitools#1]
Hi, can you provide some description/help about how to build msitools?

for example,  as [proxychains-ng README](https://github.com/rofl0r/proxychains-ng) described,  after i run

```shell
./configure --prefix=/usr --sysconfdir=/etc
make
sudo make install
sudo make install-config (installs proxychains.conf)
```
i would get `proxychains4` installed.

**Comment by tm604** [comment]
It should be mostly the same sequence, but:

- you'll need to run `./autogen.sh` first.
- remove the `make install-config` step at the end

Also, Ubuntu currently packages `msitools`, so unless you're planning to patch the source then `apt-get install msitools` might be a quicker option!

https://packages.ubuntu.com/search?keywords=msitools

**Comment by tm604** [comment]
(I've added a Dockerfile in 0502a5c5f4b2131a4fc42b31293369e325ec6010 which might help, just copy the steps from there and it should build, although I would recommend the upstream Ubuntu version since it's newer: https://github.com/tm604/msitools/blob/master/Dockerfile )

**Comment by def-fun** [comment]
> (I've added a Dockerfile in [0502a5c](https://github.com/tm604/msitools/commit/0502a5c5f4b2131a4fc42b31293369e325ec6010) which might help, just copy the steps from there and it should build, although I would recommend the upstream Ubuntu version since it's newer: https://github.com/tm604/msitools/blob/master/Dockerfile )

Thanks,  😁
